name: .NET Web API CI

on:
  push:
    branches: [ "main" ]   # Runs on pushes to main
  pull_request:
    branches: [ "main" ]   # Runs on PRs to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # change if you use 8.0, 7.0, etc.

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests (if you have a test project)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
